### ISSUE TITLE
programma hello world

### ISSUE THREAD

**Issue by FabioZTessitore** [gianlucascuncio/helloword#1]
Da terminale lancia il comando

``` bash
git clone https://github.com/gianlucascuncio/helloword.git
```

Verrà creata una directory con una copia della repository

**Comment by gianlucascuncio** [comment]
Così facendo mi esce che devo istallare apt-get

**Comment by FabioZTessitore** [comment]
probabilmente devi installare git attraverso apt-get

``` bash
$ sudo apt-get update
$ sudo apt-get install git
```

**Comment by gianlucascuncio** [comment]
si , ho fatto cosi
 ~$ sudo apt-get 
e poi mi ha fatto mettere una password

**Comment by FabioZTessitore** [comment]
Dopo apt-get cosa hai scritto?

**Comment by gianlucascuncio** [comment]
niente, ho premuto invio e mi è uscito
uso:
comandi:
opzioni:

**Comment by FabioZTessitore** [comment]
appunto. Rileggiti cosa ti avevo scritto di fare

**Comment by gianlucascuncio** [comment]
mi sta scaricando dei pacchetti

**Comment by gianlucascuncio** [comment]
ora che ha fatto mi dice che dopo questa operazione verranno occupati 22 MB di spazio sul disco...
continuo

**Comment by gianlucascuncio** [comment]
cloning into "helloword" mi esce dopo aver fatto tutto

**Comment by FabioZTessitore** [comment]
Bene. Hai installato git e quindi hai potuto fare git clone

Ora crea un file hello.c all'interno di questa directory. Deve essere un
file C che stampa un saluto

Il domenica 10 gennaio 2016, gianlucascuncio notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
Sono in attesa di notizie. Sei riuscito a compilare ed eseguire il programma da terminale?

**Comment by gianlucascuncio** [comment]
Prof devo comprare l'alimentatore che il mio se rotto e tengo la batteria
scarica al pc

**Comment by FabioZTessitore** [comment]
ok, avvisami quando sei pronto a continuare

**Comment by gianlucascuncio** [comment]
Appena compro l'alimentatore continuo subito
